version: '3'

services:
  php:
    image: Pal-comp:5000/php-fpm:8.1
    ports:
      - 9000:9000
    volumes:
      - $PWD/nginx/sites/test/www/:/var/www/default/htdocs
  web:
    image: 'Pal-comp:5000/nginx:latest'
    volumes:
      - $PWD/nginx/configs/nginx.conf:/etc/nginx/nginx.conf
      - $PWD/nginx/configs/sites/:/etc/nginx/conf.d/
      - $PWD/nginx/sites/test/www/:/var/www/default/htdocs
      - $PWD/nginx/logs/:/var/log/nginx/
    ports:
     - "8080:80"


#docker run --rm -d -v /Projects/docker_swarm/nginx_php-fpm/nginx/sites/test/www:/var/www/default/htdocs --name php -t devilbox/php-fpm:8.1-prod
